### ISSUE TITLE
Worked example: How to ask for coding help in Slack

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-july-training#11]
In the first 30 min breakout session, we intend to cover our best tips for getting help in the `#2020-july-training` Slack channel. The idea here is to provide _a worked example_ of how to ask for help. I expect the following would be covered:

1) Inserting a code block with the code that produced an error
2) Making sure to copy the text of the error
3) When screenshots are helpful – providing context, I can imagine a situation where a screenshot that has a few chunks in it, captures the error message, and the code block immediately preceding the error is pasted in would be very helpful
4) Threading - both when first asking the question and when returning to the same notebook a few steps later with a new question (helps with context if a different instructor answers the question and in a way that requires less explanation on the participant's part!)

My thought would be to add this as `workshop/slack-example.md` if we think it'd be beneficial to have a separate document we can link to _or_ in `virtual-setup/slack-procedures.md`. Revisiting the Slack procedures...that document isn't too too long so that may be ideal!

We should then link to this in the following places:

* Workshop structure (`workshop/workshop-structure.md`)  
  * In the Consultation Sessions table "I have a question about an exercise notebook"
  * `workshop/workshop-structure.md#consultation-sessions` 
  * `workshop/workshop-structure.md#using-communication-platforms-during-consultation-sessions`
* When we introduce the workshop structure in the home page `workshop/HOME.md#workshop-structure`

**Comment by cansavvy** [comment]
I think it's own document: `workshop/slack-example.md` which is linked to in `virtual-setup/slack-procedures.md` sounds good.

**Comment by jashapiro** [comment]
I believe this is done and we can close it?
