### ISSUE TITLE
Links to Docker installation instructions are broken

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-july-training#14]
In "Using Docker Post-Workshop." They should go to `docker-install/INSTALLATION-INSTRUCTIONS` not `workshop/INSTALLATION-INSTRUCTIONS`.

**Comment by cbethell** [comment]
I can work on this ticket 👍

**Comment by cbethell** [comment]
This has been addressed by merged PR #16 👍
