### ISSUE TITLE
Slides: Introduction to the Workshop

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-july-training#3]
Add PDF version of introduction to the workshop slides to `slides`.

**Comment by jaclyn-taroni** [comment]
It makes sense to me to have the very last thing we do as part of the introduction to the workshop is copy the directories required for the workshop to their home directories (see: https://github.com/AlexsLemonade/training-admin/issues/363).

Here's the transition I'm envisioning - last slide contains the relevant command, everyone opens RStudio Server (including the instructor), the host of the meeting also pastes the command in Zoom chat (to everyone) and in the Slack channel.

**Comment by jashapiro** [comment]
Updated slides are here: https://docs.google.com/presentation/d/1fB0nW2Pc59gnbbMnfG_Ul6r1VDrfojRCh83aZumSSes
