### ISSUE TITLE
Docker image with same dependencies as RStudio Server

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2020-july-training#7]
Here's a starting point: https://github.com/AlexsLemonade/2020-may-training/blob/1636e5c3495ad78cdea72051e971bf735e35eaf0/docker/Dockerfile

The `Dockerfile` should be stored in this repository (`docker/Dockerfile`) and we should push to `ccdl/training_rnaseq:2020-july` (and `latest`, as well).  The `_config.yaml` file should be updated to account for the correct repo and tag.

**Comment by jaclyn-taroni** [comment]
The [changes in the file](https://github.com/AlexsLemonade/training-admin/compare/jashapiro/R-package-updates) R package installation on the server can be used as a guide.

**Comment by jaclyn-taroni** [comment]
I have a relatively heavy meeting tomorrow and a bunch of admin tasks to catch up on, so I can pick this up since I suspect there will be a lot waiting for things to build.

**Comment by jaclyn-taroni** [comment]
@jashapiro I expect we're going to need snakemake on this Docker image. Do you have a script with all of the pip install steps for the server somewhere? I didn't see one in `training-admin` but I might be looking in the wrong place.

**Comment by jashapiro** [comment]
It isn't in a self-contained script, but the documentation is here: https://github.com/AlexsLemonade/training-admin/blob/master/virtual-procedures/RStudio-server-setup.md

**Comment by jaclyn-taroni** [comment]
Perfect thank you! I was looking in `scripts`
